### ISSUE TITLE
Add more fixtures

### ISSUE THREAD

**Issue by nagno** [MageTest/BehatMage#32]
Hello,

Could you please add fixtures for the following:
- order
- invoice
- shipping
- creditmemo

Thanks,
Norbert

**Comment by jamescowie** [comment]
We have moved fixture generation into another extension `MageManager` for the branch Behat3 I removed all fixtures. Currently we have some of the above fixtures generated but it still requires some work to complete. However the generation is now done using YAML files with the potential to specifiy different drives PHP, XML etc to create these. 

I will move this issue over to that project and when I get the time will try and add these fixtures into the project.
