### ISSUE TITLE
Status of the project ? 

### ISSUE THREAD

**Issue by ghost** [MageTest/BehatMage#6]
This project is quite interesting but do you have any status or the list of things need to be done. I can help with some :)

**Comment by MarcelloDuarte** [comment]
It's on hold now. But we are planning to put some considerate effort on this in the near future. I will let you know and definitely accept your help. Thanks!

**Comment by ghost** [comment]
@MarcelloDuarte Thanks for your status, cannot wait to see it happens in the most complex and untested but great ecommerce system :D

**Comment by alistairstead** [comment]
This project is back under active development and is also accepting contributions: https://github.com/MageTest/BehatMage/blob/develop/contributing.md
