### ISSUE TITLE
[ReflectionException]  Class Mage_Core_Model_Config_Data does not exist

### ISSUE THREAD

**Issue by aldosuwandi** [MageTest/BehatMage#63]
Hi, I have just followed your tutorial to setup magento with behat. After I added this in my behat.yml :

default:
  extensions:
    MageTest\MagentoExtension\Extension:
      base_url: "http://mywebsite.local.com"

Then, I executed bin/behat and I got this error in my terminal : 
[ReflectionException] 
  Class Mage_Core_Model_Config_Data does not exist

**Comment by vernard** [comment]
Can you please post your composer.json file? You might have forgotten to add a few lines at the autoload part.

**Comment by jamescowie** [comment]
You will get this error if you have not updated the autoload section within composer.json Example being

``` json
"autoload": {
        "psr-0": {
            "":[
                "vendor/magetest/magento/src/app",
                "vendor/magetest/magento/src/lib",
                "vendor/magetest/magento/src/app/code/local",
                "vendor/magetest/magento/src/app/code/community",
                "vendor/magetest/magento/src/app/code/core"
            ]
        }
    },
```

Replace vendor... with the path to Magento within your project. If this does not resolve the problem please re open the ticket.
