### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused / Connection to Redis failed after 2 failures

### ISSUE THREAD

**Issue by jimains** [MageTest/BehatMage#68]
I am able to run Behat and test various scenarios that I have defined but when include: MageTest\MagentoExtension\Extension: ~ within my behat.yml file I get <pre>SQLSTATE[HY000] [2002] Connection refused</pre> or a redis error if enabling redis in the Magento config.

Connecting to my Magento instance only seems to be an issue when including this module. I am thinking it might be to do with the way i am adding it to behat.yml or the way i installed using composer ("magetest/magento-behat-extension": "dev-develop").

I am using a VM to run my site but am ruling access issues out due to the fact i can connect via a browser or Behat once this module is removed. 

Any ideas? I really want to use and contribute to this module, it looks like a great project.

**Comment by debo** [comment]
Hi @jimains by the sound of it it looks like you are trying to run your features from the host machine instead of the guest VM. Is that the case? If so run the test from the guest or expose the services you need to connect to so that behat can access them from the host.

I hope that helps.

**Comment by jamescowie** [comment]
Hello @jimains did you try to run Behat from inside your VM as per @MarcelloDuarte suggestion ? Interested to get your feedback
