### ISSUE TITLE
Selenium 2 webdriver not found bug

### ISSUE THREAD

**Issue by toonvd** [MageTest/BehatMage#75]
Hi,

I am using this setup in combination with the latest selenium rc.
Everytime i pass a condition into my wait like: 

<addr>$this->getSession()->wait(5000, "$('testdiv').visible()");</addr>

I get the following error:

<addr>Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
    System info: host: 'toonvd-Precision-M4600', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.8.0_20'
    Driver info: driver.version: unknown
</addr>

This was not a problem with the old version of this repo (like 6 months ago).
Do you guys have any ideas on how to fix this?

Thx

**Comment by jamescowie** [comment]
Sorry for the delay in replying. have you updated firefox or selenium recently ? Firefox will be set in your Behat.yml file alternatives could be chrome etc. If you can past in your behat.yml and try updating selenium etc. As well as providing versions of each tool I will be happy to help more.

**Comment by toonvd** [comment]
When using chrome, the problem is not present. Will close this atm.
